### ISSUE TITLE
Release the package to Conda Forge

### ISSUE THREAD

**Issue by zkrolikowski-vl** [VirtusLab/pandas-stubs#10]
This task involves creating a necessary step in `.circleci/config.yml`, and creating an account on conda-forge.

**Comment by hpomorski** [comment]
I'l be looking at it.

**Comment by hpomorski** [comment]
Opened PR #12 in order to satisfy requirements for the conda-forge packaging.

**Comment by hpomorski** [comment]
Package is available on conda forge: https://anaconda.org/conda-forge/pandas-stubs
