### ISSUE TITLE
pd.concat() missing stubs for Iterable[Series]

### ISSUE THREAD

**Issue by janosh** [VirtusLab/pandas-stubs#111]
I'm getting:

> mypy(error): Argument 1 to "concat" has incompatible type "List[Union[DataFrame, Series]]"; expected "Iterable[DataFrame]"

[`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) accepts lists of either `Series` or `DataFrames`.

**Comment by zkrolikowski-vl** [comment]
No solution was provided for problem but pandas-stubs has moved to another repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version pip install pandas-stubs==1.4.2.220626 which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
