### ISSUE TITLE
More strict type for matrix multiplication

### ISSUE THREAD

**Issue by nagrael2** [VirtusLab/pandas-stubs#115]
When using in DataFrame `dot` or `@` pandas will return Series only when other is Series. 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dot.html

Same can be told about Series. Result of Series @ Series is Scalar, Series @ DataFrame is Series, Series @ array is array.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dot.html

Reflected operands should also be included.

**Comment by joannasendorek** [comment]
Hi @nagrael2,
Thanks for reporting the issue. You can see PR with the fix: https://github.com/VirtusLab/pandas-stubs/pull/132
