### ISSUE TITLE
arg-type error with `itertuples(name=None)`

### ISSUE THREAD

**Issue by aloysius-lim** [VirtusLab/pandas-stubs#118]
`pandas.DataFrame.itertuples` allows `name=None`. But with the following code:

```python
# df is a pandas.DataFrame.
df.itertuples(name=None)
```

Mypy reports the following error:

```
error: Argument "name" to "itertuples" of "DataFrame" has incompatible type "None"; expected "str"  [arg-type]
```

**Comment by zkrolikowski-vl** [comment]
Hi @aloysius-lim. Thank you for reporting. I've prepared a PR: https://github.com/VirtusLab/pandas-stubs/pull/119

**Comment by zkrolikowski-vl** [comment]
@aloysius-lim The fix should be now out on PyPI, and on conda-forge later today.
