### ISSUE TITLE
Positional values for usecols in read_csv not allowed anymore

### ISSUE THREAD

**Issue by edran** [VirtusLab/pandas-stubs#120]
Today I noticed that upgrading from `1.2.0.31` to `1.2.0.38` breaks our mypy checks with code that looks like:

```py
pd.read_csv(path, header=0, usecols=[0, 1, 2])
```

Removing `usecols` fixes the issue, but positional indices are generally allowed by pandas: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas-read-csv

**Comment by zkrolikowski-vl** [comment]
Hi @edran. Thanks for reporting this.

Could you share the mypy output, it's version and `pandas` version? I'm having difficulty replicating this.

**Comment by ChiaraMC** [comment]
Hello, here's the mypy output for the same issue:

```bash
file.py:10: error: No overload variant of "read_csv" matches argument types "str", "int", "List[int]"
file.py:10: note: Possible overload variant:
file.py:10: note:     def read_csv(filepath_or_buffer: Any, sep: str = ..., delimiter: Optional[str] = ..., header: Union[int, List[int], str, None] = ..., names: Union[ExtensionArray, ndarray[Any, Any], None] = ..., index_col: Union[int, str, Sequence[int], Sequence[str], bool, None] = ..., usecols: Union[ExtensionArray, ndarray[Any, Any], Callable[[Any], Any], None] = ..., squeeze: bool = ..., prefix: str = ..., mangle_dupe_cols: bool = ..., dtype: Any = ..., engine: Union[Literal['c'], Literal['python'], None] = ..., converters: Optional[Dict[Any, Any]] = ..., true_values: Optional[List[Any]] = ..., false_values: Optional[List[Any]] = ..., skipinitialspace: bool = ..., skiprows: Union[ExtensionArray, ndarray[Any, Any], int, Callable[[Any], Any], None] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[str, int, float, bool, Any, bool_, bool_, Any, signedinteger[Any], Any, signedinteger[Any], Any, signedinteger[Any], signedinteger[Any], signedinteger[Any], signedinteger[_8Bit], signedinteger[_16Bit], signedinteger[_32Bit], signedinteger[_64Bit], unsignedinteger[Any], unsignedinteger[Any], Any, unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[_8Bit], unsignedinteger[_16Bit], unsignedinteger[_32Bit], unsignedinteger[_64Bit], floating[Any], floating[Any], Any, floating[Any], floating[Any], floating[_16Bit], floating[_32Bit], floating[_64Bit], floating[_128Bit], complexfloating[Any, Any], Any, complexfloating[Any, Any], complexfloating[Any, Any], complexfloating[_32Bit, _32Bit], complexfloating[_64Bit, _64Bit], complexfloating[_96Bit, _96Bit], complexfloating[_128Bit, _128Bit], Decimal, ByteString, Fraction, DateOffset, Interval, Number, datetime, timedelta, str, ExtensionArray, ndarray[Any, Any], Dict[Any, Any], None] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], List[List[Any]], Dict[Any, Any]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Optional[Callable[[Any], Any]] = ..., dayfirst: bool = ..., cache_dates: bool = ..., *, iterator: Literal[False] = ..., chunksize: None = ..., **kwargs: Any) -> DataFrame
file.py:10: note:     <2 more non-matching overloads not shown>
```

Pandas version: 1.3.4, mypy version: 0.910

From the [read_csv stubs](https://github.com/VirtusLab/pandas-stubs/blob/e3f72642983308f3bd4dd506acd97173286bae63/third_party/3/pandas/io/parsers/readers.pyi):
```py
usecols: Optional[Union[ArrayLike, AnyCallable]]
```
I *think* Pandas' `ArrayLike` doesn't include Lists (wrapping the list in `np.array` removes the error).

**Comment by nahuelalmeira** [comment]
Hi @zkrolikowski-vl, I am experiencing the same error. Here is the output I get

`
test_usecols.py:3: error: No overload variant of "read_csv" matches argument types "str", "List[str]"
test_usecols.py:3: note: Possible overload variants:
test_usecols.py:3: note:     def read_csv(filepath_or_buffer: Any, sep: str = ..., delimiter: Optional[str] = ..., header: Union[int, List[int], str, None] = ..., names: Union[ExtensionArray, ndarray[Any, Any], None] = ..., index_col: Union[int, str, Sequence[int], Sequence[str], bool, None] = ..., usecols: Union[ExtensionArray, ndarray[Any, Any], Callable[[Any], Any], None] = ..., squeeze: bool = ..., prefix: str = ..., mangle_dupe_cols: bool = ..., dtype: Any = ..., engine: Union[Literal['c'], Literal['python'], None] = ..., converters: Optional[Dict[Any, Any]] = ..., true_values: Optional[List[Any]] = ..., false_values: Optional[List[Any]] = ..., skipinitialspace: bool = ..., skiprows: Union[ExtensionArray, ndarray[Any, Any], int, Callable[[Any], Any], None] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[str, int, float, bool, Any, bool_, bool_, Any, signedinteger[Any], Any, signedinteger[Any], Any, signedinteger[Any], signedinteger[Any], signedinteger[Any], signedinteger[_8Bit], signedinteger[_16Bit], signedinteger[_32Bit], signedinteger[_64Bit], unsignedinteger[Any], unsignedinteger[Any], Any, unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[_8Bit], unsignedinteger[_16Bit], unsignedinteger[_32Bit], unsignedinteger[_64Bit], floating[Any], floating[Any], Any, floating[Any], floating[Any], floating[_16Bit], floating[_32Bit], floating[_64Bit], floating[_128Bit], complexfloating[Any, Any], Any, complexfloating[Any, Any], complexfloating[Any, Any], complexfloating[_32Bit, _32Bit], complexfloating[_64Bit, _64Bit], complexfloating[_96Bit, _96Bit], complexfloating[_128Bit, _128Bit], Decimal, ByteString, Fraction, DateOffset, Interval, Number, datetime, timedelta, str, ExtensionArray, ndarray[Any, Any], Dict[Any, Any], None] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], List[List[Any]], Dict[Any, Any]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Optional[Callable[[Any], Any]] = ..., dayfirst: bool = ..., cache_dates: bool = ..., *, iterator: Literal[True], chunksize: Optional[int] = ..., **kwargs: Any) -> TextFileReader
test_usecols.py:3: note:     def read_csv(filepath_or_buffer: Any, sep: str = ..., delimiter: Optional[str] = ..., header: Union[int, List[int], str, None] = ..., names: Union[ExtensionArray, ndarray[Any, Any], None] = ..., index_col: Union[int, str, Sequence[int], Sequence[str], bool, None] = ..., usecols: Union[ExtensionArray, ndarray[Any, Any], Callable[[Any], Any], None] = ..., squeeze: bool = ..., prefix: str = ..., mangle_dupe_cols: bool = ..., dtype: Any = ..., engine: Union[Literal['c'], Literal['python'], None] = ..., converters: Optional[Dict[Any, Any]] = ..., true_values: Optional[List[Any]] = ..., false_values: Optional[List[Any]] = ..., skipinitialspace: bool = ..., skiprows: Union[ExtensionArray, ndarray[Any, Any], int, Callable[[Any], Any], None] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[str, int, float, bool, Any, bool_, bool_, Any, signedinteger[Any], Any, signedinteger[Any], Any, signedinteger[Any], signedinteger[Any], signedinteger[Any], signedinteger[_8Bit], signedinteger[_16Bit], signedinteger[_32Bit], signedinteger[_64Bit], unsignedinteger[Any], unsignedinteger[Any], Any, unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[_8Bit], unsignedinteger[_16Bit], unsignedinteger[_32Bit], unsignedinteger[_64Bit], floating[Any], floating[Any], Any, floating[Any], floating[Any], floating[_16Bit], floating[_32Bit], floating[_64Bit], floating[_128Bit], complexfloating[Any, Any], Any, complexfloating[Any, Any], complexfloating[Any, Any], complexfloating[_32Bit, _32Bit], complexfloating[_64Bit, _64Bit], complexfloating[_96Bit, _96Bit], complexfloating[_128Bit, _128Bit], Decimal, ByteString, Fraction, DateOffset, Interval, Number, datetime, timedelta, str, ExtensionArray, ndarray[Any, Any], Dict[Any, Any], None] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], List[List[Any]], Dict[Any, Any]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Optional[Callable[[Any], Any]] = ..., dayfirst: bool = ..., cache_dates: bool = ..., *, iterator: Literal[False] = ..., chunksize: int, **kwargs: Any) -> TextFileReader
test_usecols.py:3: note:     def read_csv(filepath_or_buffer: Any, sep: str = ..., delimiter: Optional[str] = ..., header: Union[int, List[int], str, None] = ..., names: Union[ExtensionArray, ndarray[Any, Any], None] = ..., index_col: Union[int, str, Sequence[int], Sequence[str], bool, None] = ..., usecols: Union[ExtensionArray, ndarray[Any, Any], Callable[[Any], Any], None] = ..., squeeze: bool = ..., prefix: str = ..., mangle_dupe_cols: bool = ..., dtype: Any = ..., engine: Union[Literal['c'], Literal['python'], None] = ..., converters: Optional[Dict[Any, Any]] = ..., true_values: Optional[List[Any]] = ..., false_values: Optional[List[Any]] = ..., skipinitialspace: bool = ..., skiprows: Union[ExtensionArray, ndarray[Any, Any], int, Callable[[Any], Any], None] = ..., skipfooter: int = ..., nrows: Optional[int] = ..., na_values: Union[str, int, float, bool, Any, bool_, bool_, Any, signedinteger[Any], Any, signedinteger[Any], Any, signedinteger[Any], signedinteger[Any], signedinteger[Any], signedinteger[_8Bit], signedinteger[_16Bit], signedinteger[_32Bit], signedinteger[_64Bit], unsignedinteger[Any], unsignedinteger[Any], Any, unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[Any], unsignedinteger[_8Bit], unsignedinteger[_16Bit], unsignedinteger[_32Bit], unsignedinteger[_64Bit], floating[Any], floating[Any], Any, floating[Any], floating[Any], floating[_16Bit], floating[_32Bit], floating[_64Bit], floating[_128Bit], complexfloating[Any, Any], Any, complexfloating[Any, Any], complexfloating[Any, Any], complexfloating[_32Bit, _32Bit], complexfloating[_64Bit, _64Bit], complexfloating[_96Bit, _96Bit], complexfloating[_128Bit, _128Bit], Decimal, ByteString, Fraction, DateOffset, Interval, Number, datetime, timedelta, str, ExtensionArray, ndarray[Any, Any], Dict[Any, Any], None] = ..., keep_default_na: bool = ..., na_filter: bool = ..., verbose: bool = ..., skip_blank_lines: bool = ..., parse_dates: Union[bool, List[int], List[str], List[List[Any]], Dict[Any, Any]] = ..., infer_datetime_format: bool = ..., keep_date_col: bool = ..., date_parser: Optional[Callable[[Any], Any]] = ..., dayfirst: bool = ..., cache_dates: bool = ..., *, iterator: Literal[False] = ..., chunksize: None = ..., **kwargs: Any) -> DataFrame
`

Input:

`
import pandas as pd
pd.read_csv("test.csv", usecols=["A"])
`

Pandas version: 1.3.5
Mypy version 0.931

As @ChiaraMC says, wrapping the list in `np.array` solves the problem, but this shouldn't be necessary.

**Comment by zkrolikowski-vl** [comment]
Hi @nahuelalmeira. Thanks for bumping this issue up. The fix is simple enough but test cases don't work as expected. I'll try to open up a PR today.

**Comment by zkrolikowski-vl** [comment]
In the end I wasn't able to fix it but pandas-stubs has moved to new repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version pip install pandas-stubs==1.4.2.220626 which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
