### ISSUE TITLE
pd.drop() should accept Set

### ISSUE THREAD

**Issue by ChiaraMC** [VirtusLab/pandas-stubs#121]
`pd.drop()`  accepts both lists and sets (and possibly other iterables). So the following runs fine
```python
def get_my_set() -> Set[int]:
    return set([0, 3])

d = {"col1": [1, 2, 3, 4, 5], "col2": [6, 7, 8, 9, 10]}
df = pd.DataFrame(data=d)
to_drop = get_my_set()

df.drop(to_drop, inplace=True)
```
but mypy raises an error:
`No overload variant of "drop" of "DataFrame" matches argument types "Set[int]", "bool"`

while this runs fine and mypy doesn't complain:
```python
def get_my_set() -> Any:
    return set([0, 3])

d = {"col1": [1, 2, 3, 4, 5], "col2": [6, 7, 8, 9, 10]}
df = pd.DataFrame(data=d)
to_drop = get_my_set()

df.drop(to_drop, inplace=True)
```
which seems strange.

I noticed that [here](https://github.com/VirtusLab/pandas-stubs/blob/43be82b762530d9c726d72d1d68f546627e43c3c/third_party/3/pandas/core/frame.pyi) drop has been set to only accept a Sequence and not an Iterable, which explains the error. Is there a reason for this?

**Comment by zkrolikowski-vl** [comment]
Hi @ChiaraMC. While passing `Set[str]` is undocumented, it just works.

Your intuition was correct and it works with `Iterable`. 

Here's a PR for your consideration. We'll merge it soon and release a new version.
https://github.com/VirtusLab/pandas-stubs/pull/122/files

**Comment by ChiaraMC** [comment]
Hi @zkrolikowski-vl amazing, thanks for the speedy reply!

**Comment by zkrolikowski-vl** [comment]
@ChiaraMC  It's merge and a new version should be available on PyPI now and on coda-forge in a couple of hours. 

Thanks for reporting. I hope to hear about more issues you have from you!
