### ISSUE TITLE
Raise DataFrame and Series to power

### ISSUE THREAD

**Issue by janosh** [VirtusLab/pandas-stubs#135]
Unexpected `mypy` errrors

```
mypy(error): Unsupported operand types for ** ("DataFrame" and "int")
mypy(error): Unsupported operand types for ** ("Series" and "int")
```

from

```py
df ** 2
df["col"] ** 2
```

**Comment by zkrolikowski-vl** [comment]
Hi @janosh. Thanks for reporting again!

Here's a PR with a fix: https://github.com/VirtusLab/pandas-stubs/pull/136. Hopefully we can release the fix soon,

**Comment by zkrolikowski-vl** [comment]
PR has been merged. Version 1.2.0.45 should now be available through pip and conda-forge.

**Comment by janosh** [comment]
@zkrolikowski-vl Thanks! Fix confirmed.
