### ISSUE TITLE
df.mean(1) cannot be float

### ISSUE THREAD

**Issue by janosh** [VirtusLab/pandas-stubs#138]
Quite an edge case but I wonder if the type hints could be improved here:

```py
(df.filter(like="pattern") ** 2).mean(1).fillna(0)
>>> mypy(error) Item "float" of "Union[Series, float]" has no attribute "fillna"
```

Type checker correctly infers `df` to be `Dataframe` but then incorrectly thinks `df.mean(1)` could yield a float or a Series. Taking the mean along the column dimension should always yield a series.

**Comment by joannasendorek** [comment]
Hi @janosh thanks for reporting. I will look into this issue and prepare PR.

**Comment by janosh** [comment]
@joannasendorek I don't think the problem depends on the form of the dataframe. In any case, this triggers the error:

```py
import pandas as pd

df = pd.DataFrame([[1, 2, 3]], columns=["a", "b", "c"])

(df.filter(like="a") ** 2).mean(1).fillna(0)
```

**Comment by zkrolikowski-vl** [comment]
pandas-stubs has moved to new repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version pip install pandas-stubs==1.4.2.220626 which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
