### ISSUE TITLE
`DataFrame.append` has bad dictionary index types

### ISSUE THREAD

**Issue by randolf-scholz** [VirtusLab/pandas-stubs#139]
`DataFrame.append` is annotated as

https://github.com/VirtusLab/pandas-stubs/blob/292a31f4e91ca13f362299277d9bd96ebe943ce1/third_party/3/pandas/core/frame.pyi#L224

where `Column` is defined as

https://github.com/VirtusLab/pandas-stubs/blob/292a31f4e91ca13f362299277d9bd96ebe943ce1/third_party/3/pandas/_typing.pyi#L98

This fails, for example, if we pass:

- `dict[int, float]`
- `dict[str, float]`
- `dict[tuple[str, ...], float]`
- `dict[tuple[int, ...], float]`
- `dict[tuple[Union[int, float] ...], float]`
- even more complex indexing schemes.

Since `DataFrame.columns` can be an arbitrary `pandas.Index`, which supports all kinds of data types (int, float, datetime, interval, etc.) this should be replaced by `dict[Any, Any]`.

**Comment by zkrolikowski-vl** [comment]
Hi @randolf-scholz. Thanks for taking a look at this.

I've prepared a PR but it might end up being extended: https://github.com/VirtusLab/pandas-stubs/pull/140

**Comment by zkrolikowski-vl** [comment]
@randolf-scholz It's merged and the fix should be on PyPI now and conda-forge soon.
