### ISSUE TITLE
DataFrame.groupby level doesn't accept int

### ISSUE THREAD

**Issue by ChiaraMC** [VirtusLab/pandas-stubs#143]
Hello!

`pandas.DataFrame.groupby` takes the parameter `level` which according to the pandas docs can be an int. However, the current stubs require `Optional[Sequence[Union[Optional[Hashable], int]]]` which does not match a simple int.

To reproduce: 

```python
import pandas as pd

df1 = pd.DataFrame(data={"A": [1, 2]})
df2 = pd.DataFrame(data={"A": [3, 4]})

df = pd.concat([df1, df2]).groupby(level=0).mean()
```
Error:
```
mypy_mistake.py:7: error: Argument "level" to "groupby" of "DataFrame" has incompatible type "int"; expected "Optional[Sequence[Union[Optional[Hashable], int]]]"
```

Versions:
Pandas: 1.3.5,  mypy: 0.910, pandas-stubs: 1.2.0.47

**Comment by zkrolikowski-vl** [comment]
Hi @ChiaraMC. Thanks for reporting.

I've prepared a PR to fix this issue. Hopefully we'll be able to release a patch version soon.
https://github.com/VirtusLab/pandas-stubs/pull/144

**Comment by zkrolikowski-vl** [comment]
[New version](https://pypi.org/project/pandas-stubs/1.2.0.48/) has been released to PyPI. conda-forge release will follow.

Please let us know if you've come across any other issues. I'm closing this issue.
