### ISSUE TITLE
pd.Timedelta should accept kwargs

### ISSUE THREAD

**Issue by ChiaraMC** [VirtusLab/pandas-stubs#151]
Hello!

According to the docs for `pd.Timedelta` (https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.html) we can do, for example:

```python
pd.Timedelta(hours=1)
```
which is equivalent to:
```python
pd.Timedelta(value=1, unit="hours")
```

However, the current stubs accept the second version but not the first version, which instead gives:
`error: Missing positional argument "value" in call to "Timedelta"`

Same thing happens using for example "days".

Versions:
- pandas 1.4.1
- mypy 0.910
- pandas-stubs 1.2.0.48

**Comment by zkrolikowski-vl** [comment]
Hi @ChiaraMC! Thanks for reaching out.

Stubs for timedelta are still largely incomplete and mostly based of datetime.timedelta. The gap included using keyword arguments for the constructor.

I've created a PR to add this support: https://github.com/VirtusLab/pandas-stubs/pull/155 It'll soon be merged.

There are still more gaps - they'll be filled as we go along but please open an issue if you encounter any that block your work.

**Comment by zkrolikowski-vl** [comment]
Version 1.2.0.52 released with a fix.

**Comment by ChiaraMC** [comment]
I see, thanks for fixing this!
