### ISSUE TITLE
`mypy` issue when value of the dict passed to `from_dict()` are scalars

### ISSUE THREAD

**Issue by johanvergeer** [VirtusLab/pandas-stubs#152]
When a scalar value is used in the dict that is passed to `from_dict()`, then mypy will raise an error, while Pandas can handle this input just fine.

```python
>>> import pandas as pd
>>> data = {"a": 1, "b": 2}
>>> dataframe = pd.DataFrame.from_dict(data, orient="index", columns=["foo"])
>>> dataframe
   foo
a    1
b    2
```

Would it be better to change the stubs for `from_dict()` to also allow scalars?

I did have a look at the `pandas._typing` module, which contains some definitions for scalars, but that doesn't seem to include numpy types.

```python
PythonScalar = Union[str, int, float, bool]
PandasScalar = Union["Period", "Timestamp", "Timedelta", "Interval"]
Scalar = Union[PythonScalar, PandasScalar]
```

**Comment by zkrolikowski-vl** [comment]
pandas-stubs has moved to a new repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version pip install pandas-stubs==1.4.2.220626 which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
