### ISSUE TITLE
Pyright detect error when accesing dataframe from conditional creation

### ISSUE THREAD

**Issue by AchmadFathoni** [VirtusLab/pandas-stubs#156]
Using pandas-stub 1.2.0.50 and pyright  1.1.230
```
import pandas as pd

data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns = ['Name', 'Age'])
df = df[df.index > 0]
Y = df[['Name', 'Age']]
```
At last line I get `Argument of type "list[str]" cannot be assigned to parameter "key" of type "slice" in function "__getitem__"    "list[str]" is incompatible with "slice"`. Deleting `df = df[df.index > 0]` will suppress the error. Should I report to pyright instead?

**Comment by zkrolikowski-vl** [comment]
Hi @AchmadFathoni. 

I've managed to replicate the problem - it only occurs in pyright.

As you're most likely correct pandas_stubs can be used with pyright however it's not being tested on the development. https://github.com/VirtusLab/pandas-stubs/issues/160

Even without a CI I'll take this on as a one-off.

**Comment by AchmadFathoni** [comment]
Thank you, It is fixed.
