### ISSUE TITLE
"DatetimeIndex" has no attribute "strftime"

### ISSUE THREAD

**Issue by claudio-ebel** [VirtusLab/pandas-stubs#162]
### Minimal working example
```python
# ––– file strftime_bug.py
import pandas as pd
                                                                             
days: pd.DatetimeIndex = pd.date_range('2020-1-1', periods=3)
print([day for day in days.strftime("%d")])
```
### Behaviour
mypy emits error:
```bash
$ mypy strftime_bug.py
strftime_bug.py 5: error: "DatetimeIndex" has no attribute "strftime"
Found 1 error in 1 file (checked 1 source file)
```
execution works:
```bash
$ python strftime_bug.py
['01', '02', '03']
```
### Versions
```bash
$ python --version
Python 3.10.4
$ mypy --version
mypy 0.942
$ pip freeze | grep stub
pandas-stubs==1.2.0.56
```

**Comment by zkrolikowski-vl** [comment]
pandas-stubs has moved to a new repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version pip install pandas-stubs==1.4.2.220626 which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
