### ISSUE TITLE
Assigning to a dataframe causes type error

### ISSUE THREAD

**Issue by thomas-intellegens** [VirtusLab/pandas-stubs#163]
Assigning to a DataFrame's index property now raises a type error. The behaviour of doing so is documented (https://pandas.pydata.org/docs/user_guide/indexing.html#adding-an-ad-hoc-index), so I would expect no type error.

```python
import pandas as pd

f = pd.DataFrame(([1, 2, 3], [4, 5, 6]))
f.index = pd.Index(["a", "b"]) # this returns a type error
```

This appears to have been introduced in #161 by not providing a setter to go with the property.

Tested on pyright 1.1.235, mypy 0.910 and PyCharm 2021.3.3 against python 3.8.10 on Ubuntu 20.04.4 LTS

mypy
```
error: Property "index" defined in "NDFrame" is read-only
```

pyright
```
error: Cannot assign member "index" for type "DataFrame"
```

PyCharm
```
Property 'index' cannot be set
```

**Comment by zkrolikowski-vl** [comment]
Hi @thomas-intellegens and thanks for correct diagnosis. 

I've created a fix https://github.com/VirtusLab/pandas-stubs/pull/165 Version [1.2.0.56](https://github.com/VirtusLab/pandas-stubs/commit/545fae0770e3eacf5dfe17588f3a79cd7d27819d) which included this fix will be released momentarily.

Feel free to open more issues for any problems you encounter. Thanks again!
