### ISSUE TITLE
Type of DataFrame.select_dtypes doesn't permit scalars

### ISSUE THREAD

**Issue by thomas-intellegens** [VirtusLab/pandas-stubs#166]
DataFrame.select_dtypes currently only accepts iterables of types, where the pandas also permits it to be a scalar type (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html).

```python
f = pd.DataFrame([[1, "2", 3]], ["A"], ["a", "b", "c"])
t = f.select_dtypes(include=np.number)  # Causes error
```

Tested with mypy 0.910, pyright 1.1.236 and PyCharm 2021.3.3 against python 3.8.10 on Ubuntu 20.04.4 LTS.

mypy

```
error: Argument "include" to "select_dtypes" of "DataFrame" has incompatible type "Type[number[Any]]"; expected "Optional[Sequence[Union[str, Any]]]"
```

pyright
```
error: Argument of type "Type[number[Unknown]]" cannot be assigned to parameter "include" of type "Sequence[str | Any] | None" in function "select_dtypes"
    Type "Type[number[Unknown]]" cannot be assigned to type "Sequence[str | Any] | None"
      "Type[type]" is incompatible with "Type[Sequence[str | Any]]"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)
```
pycharm
```
Expected type 'Optional[Sequence[Union[str, Any]]]', got 'Type[number]' instead
```

**Comment by zkrolikowski-vl** [comment]
Hi @thomas-intellegens. Thanks for reporting a problem again.

Please consider if: https://github.com/VirtusLab/pandas-stubs/pull/167 covers your use case.

**Comment by zkrolikowski-vl** [comment]
Merged the PR. Closing the issue

**Comment by thomas-intellegens** [comment]
Many thanks for responding so promptly, this is great.
