### ISSUE TITLE
error: Module has no attribute "is_numeric_dtype"  [attr-defined]

### ISSUE THREAD

**Issue by hwchase17** [VirtusLab/pandas-stubs#168]
this is caused by 
```
import pandas as pd
pd.api.types.is_numeric_dtype
```

using
```
-> pip freeze | grep pandas
pandas==1.4.2
pandas-stubs==1.2.0.58
```

and

```
-> pip show mypy
Name: mypy
Version: 0.942
Summary: Optional static typing for Python
Home-page: http://www.mypy-lang.org/
Author: Jukka Lehtosalo
Author-email: jukka.lehtosalo@iki.fi
License: MIT License
Requires: mypy-extensions, tomli, typing-extensions
Required-by:
```
on mac M1

**Comment by zkrolikowski-vl** [comment]
pandas-stubs has moved to a new repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version pip install pandas-stubs==1.4.2.220626 which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
