### ISSUE TITLE
Future:  pandas team to provide pandas-stubs

### ISSUE THREAD

**Issue by Dr-Irv** [VirtusLab/pandas-stubs#172]
The pandas team has taken the work done here and the work done by Microsoft at https://github.com/microsoft/python-type-stubs/tree/main/partial/pandas and have created a new project https://github.com/pandas-dev/pandas-stubs that will eventually become the official pandas stubs supported by the pandas core team.

We anticipate creating a release on pypi and conda by the end of June, 2022.

A big thank you to the owners and maintainers of this project for creating a testing environment and working with the pandas core team to make this happen.

**Comment by BrenoJesusFernandes** [comment]
That's incredible! Are you guys will support just the newer versions or the older versions too?

**Comment by Dr-Irv** [comment]
> That's incredible! Are you guys will support just the newer versions or the older versions too?

By "you guys", I think you mean the pandas core team.  If so, we still have to figure out a support policy with respect to old/new versions, but most likely the first release will support only the latest version of pandas (currently 1.4.2).  We will also have version numbers of the stubs, so, for example, if we release a stubs version compatible with 1.4.2, and then a pandas release of 1.5, and then new stubs for pandas 1.5 support, you could grab a version of the stubs that was compatible with 1.4.2 and a version compatible with 1.5 by referring to the appropriate pandas-stubs versions.

Hope that helps.

**Comment by zkrolikowski-vl** [comment]
Please consider this PR: https://github.com/VirtusLab/pandas-stubs/pull/175
