### ISSUE TITLE
to_markdown wrong hint

### ISSUE THREAD

**Issue by nlyf** [VirtusLab/pandas-stubs#173]
Hi, as I can see pandas.dataframe.[to_markdown ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html)returns str

Why do we have return type [Optional](https://github.com/VirtusLab/pandas-stubs/blob/6ddb27f7c7f77d27f83beaba03ce5b86314cc04e/third_party/3/pandas/core/series.pyi#L125)[str]? Is this a little bug?

**Comment by zkrolikowski-vl** [comment]
pandas-stubs has moved to a new repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version `pip install pandas-stubs==1.4.2.220626` which comes from that repository. If it doesn't work please considering opening an issue in the new repository.
