### ISSUE TITLE
`DataFrame.__getitem__(self, key: Sequence[Column])` stub definition

### ISSUE THREAD

**Issue by bzoracler** [VirtusLab/pandas-stubs#23]
I believe that there are two issues with the overload `DataFrame.__getitem__(self, key: Sequence[Column])`. However, I don't really know the intention behind this hint (specifically what `Sequence[Column]` is supposed to be) - so I hope some light could be shed on this stub. My interpretation is that the intended meaning of `Sequence[Column]` is something like `typing.List[Column]` and **not** `typing.Tuple[Column]`, and the following issues are based on this interpretation.

---

### 1. Return type hint

https://github.com/VirtusLab/pandas-stubs/blob/9751bff3b1716f0731d91313c059bdcf95244cd5/third_party/3/pandas/core/frame.pyi#L78-L79

https://github.com/VirtusLab/pandas-stubs/blob/9751bff3b1716f0731d91313c059bdcf95244cd5/third_party/3/pandas/_typing.pyi#L104

It looks like the return hint should be `DataFrame`, not `Series`. E.g.

```
>>> import pandas as pd
>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], 8: [7, 8, 9]})
>>> df
   A  B  8
0  1  4  7
1  2  5  8
2  3  6  9
>>> df[["A", 8]]
   A  8
0  1  7
1  2  8
2  3  9
>>> df[["A", 8]].__class__
<class 'pandas.core.frame.DataFrame'>
>>> df["A"].__class__
<class 'pandas.core.series.Series'>
>>> df[["A"]].__class__
<class 'pandas.core.frame.DataFrame'>
```

---

### 2. Type hint of `key`
`Sequence` is from the base `typing` module,

https://github.com/VirtusLab/pandas-stubs/blob/9751bff3b1716f0731d91313c059bdcf95244cd5/third_party/3/pandas/core/frame.pyi#L20-L21

and according to https://docs.python.org/3/glossary.html#term-sequence

> ### sequence
> An iterable which supports efficient element access using integer indices via the \_\_getitem\_\_() special method and defines a \_\_len\_\_() method that returns the length of the sequence. Some built-in sequence types are list, str, **tuple**, and bytes.

Since `typing.Sequence` covers `tuple` objects, the stub conflicts with the following behaviour:

```
>>> import pandas as pd
>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], 8: [7, 8, 9]})
>>> 
>>> df[("A", 8)]
Traceback (most recent call last):
  File "~/[venv]/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('A', 8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/[venv]/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "~/[venv]/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('A', 8)

```

`tuple` objects get treated as the same as `Column` objects in the following overload:

https://github.com/VirtusLab/pandas-stubs/blob/9751bff3b1716f0731d91313c059bdcf95244cd5/third_party/3/pandas/core/frame.pyi#L76-L77

E.g.

```
>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], ("C", int, (99,)): [7, 8, 9]})
>>> df
   A  B  (C, <class 'int'>, (99,))
0  1  4                          7
1  2  5                          8
2  3  6                          9
>>> df[("C", int, (99,))]
0    7
1    8
2    9
Name: (C, <class 'int'>, (99,)), dtype: int64
>>> df[("C", int, (99,))].__class__
<class 'pandas.core.series.Series'>
>>> df[("C", int, (99,))].to_frame()
              C
  <class 'int'>
          (99,)
0             7
1             8
2             9
```

**Comment by zkrolikowski-vl** [comment]
Thanks for finding this. I was able to work out some better types that match real use. I've also added tests. Please review:
https://github.com/VirtusLab/pandas-stubs/pull/24

There's still an slight issue when I run mypy locally. I've tried this declaration:
```
    @overload
    def __getitem__(self, key: Column) -> Series: ...
    @overload
    def __getitem__(self, key: Union[Series, Index, DataFrame, List[Column], slice, np.ndarray]) -> DataFrame: ...
 ```
 however then I get this error from mypy:
 ```
 third_party/3/pandas/core/frame.pyi:77: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
 ```
it says that `Column` (`Union[int,str]`) overlaps `np.ndarray` which is absolutely ludicrous. 

I'm looking into possible reasons but for now it looks like a mypy bug. I'm able to replicate this in other classes:
```
from typing import overload
import numpy as np

class A:
    @overload
    def a(self, key: int) -> int: ...
    @overload
    def a(self, key: np.ndarray) -> str: ...
```

reports the same issue.

I worked around this with `#type: ignore`, and this works well for disabling a local check for this, but it still looks like a bug to me.
