### ISSUE TITLE
Timestamp does not have a signature

### ISSUE THREAD

**Issue by daviskirk** [VirtusLab/pandas-stubs#28]
The current type annotations for `pandas.Timestamp` (https://github.com/VirtusLab/pandas-stubs/blob/master/third_party/3/pandas/_libs/tslibs/timestamps.pyi) does not hae a signature, where in reality it does: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html

This leads to mypy complaining with the error:

```
error: Too many arguments for "Timestamp"
```

for code like:

```
import pandas
pandas.Timestamp("2021-01-01")
```

Same problem for Timedelta:

```
import pandas
pandas.Timedelta("1s")
```

**Comment by zkrolikowski-vl** [comment]
Fixing that. I'll let you know when it's ready for review.

**Comment by zkrolikowski-vl** [comment]
Ok. There was a lot of declarations missing so I've tried my best to get them back in. 

What's most important is your problem. Do the following test cases cover it: https://github.com/VirtusLab/pandas-stubs/blob/2677dcd92617a7d55bb27bead7922341dd4341d7/tests/snippets/test_timestamp.py

**Comment by daviskirk** [comment]
> Ok. There was a lot of declarations missing so I've tried my best to get them back in.
> 
> What's most important is your problem. Do the following test cases cover it: https://github.com/VirtusLab/pandas-stubs/blob/2677dcd92617a7d55bb27bead7922341dd4341d7/tests/snippets/test_timestamp.py

Commented here:

https://github.com/VirtusLab/pandas-stubs/pull/30/files#r593245488

**Comment by daviskirk** [comment]
A general Question for the future: Are these types manually edited or are they autogenerated in some way?
Or asked a different way: If I find other stuff can I should just submit a pull request with the manual changes or is there a magic  generator script that makes that unnecessary?

**Comment by zkrolikowski-vl** [comment]
Initial version was generated using `stubgen` but only about 10-20% of the code had annotations.

So unfortunately most of the work is manual. There's no magic tool. :/

This is a special case because stubgen has created at least an untyped constructor but that code was mistakenly removed.

**Comment by zkrolikowski-vl** [comment]
Merged the PR and released a new package with the fix.
