### ISSUE TITLE
DataFrame methods should return DataFrame *or* None rather than Optional[DataFrame]

### ISSUE THREAD

**Issue by yobiscus** [VirtusLab/pandas-stubs#31]
## Problem summary:

I noticed a few methods that are returning Optional[DataFrame], e.g.:

```python
def drop(self, ...) -> Optional[DataFrame]: ...
def rename(self, ...) -> Optional[DataFrame]: ...
```

from [pandas/core/frame.pyi](https://github.com/VirtusLab/pandas-stubs/blob/master/third_party/3/pandas/core/frame.pyi).

It appears to me that these methods may return None because when `inplace=True`, a dataframe is not returned, and so _most of the time_, these methods will actually return a dataframe.

The current API as it is defined makes it difficult to adopt these stubs because the user must always assert that the dataframe is not None, which makes the code overly verbose (especially when using method chaining).

## Proposal

I'm proposing that the stubs be updated to use [typing overload](https://docs.python.org/3/library/typing.html#typing.overload). This would allow us to specify different type signatures for `inplace=True` and `inplace=False`.

Are my assumptions correct? Does this sound reasonable? I can open a PR for this if there is interest.

**Comment by zkrolikowski-vl** [comment]
Yes, your assumptions are correct and using the "inplace" methods is difficult.

A PR would be much appreciated, or at least a valid approach to dealing with this. One probable solution would be declaring these overloaded argument types as `Literal[True]` and `Literal[False]`.

**Comment by zkrolikowski-vl** [comment]
@yobiscus Here's a PR for your consideration. 

This solved the issue but there's a side effect: the `inplace` parameter is now keyword only due to mypy limitations on overloading with parent class methods.

**Comment by zkrolikowski-vl** [comment]
Fixed by: https://github.com/VirtusLab/pandas-stubs/pull/32

**Comment by yobiscus** [comment]
Great! Thank you @zkrolikowski-vl. I started working on a PR for this but unfortunately got side-tracked. I noticed limitations similar to what you mention here, especially for methods that support **kwargs. I'm looking forward to picking up these changes.
