### ISSUE TITLE
pd.read_excel arg "sheet_name" accepts only "int"

### ISSUE THREAD

**Issue by headtr1ck** [VirtusLab/pandas-stubs#34]
Pandas `read_excel` argument sheet_name supports "str, int, list, or None" according to the docu.
https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

The stubs only accept int.
This should be replaced by `Optional[Union[str, int, Sequence]]`, or simply `Optional[Any]` as often used here.

**Comment by zkrolikowski-vl** [comment]
Hi Mick,

here's a PR for your consideration: https://github.com/VirtusLab/pandas-stubs/pull/35

**Comment by headtr1ck** [comment]
Thats the fastest PR I have ever witnessed :1st_place_medal: amazing.
