### ISSUE TITLE
Wrong type stub for pandas.to_datetime()

### ISSUE THREAD

**Issue by derhintze** [VirtusLab/pandas-stubs#38]
We use the datetime conversion function of pandas like:

```
date = pd.to_datetime(times, unit="s", origin=pd.Timestamp("01/01/2000"))
```

However, having the stubs installed, mypy complains that

```
error: Argument "origin" to "to_datetime" has incompatible type "Timestamp"; expected "str"
```

The pandas docs list, after some strings, also "Timestamp convertible" (and passing in that `pd.Timestamp` for `origin` actually works at runtime): https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

Positive check: casting the `pd.Timestamp` to `str` before passing it to `origin` removes the mypy error.

**Comment by zkrolikowski-vl** [comment]
Thanks @derhintze. We'll have a fix ready soon.

**Comment by joannasendorek** [comment]
Solved by: https://github.com/VirtusLab/pandas-stubs/pull/40
