### ISSUE TITLE
pd.concat(dict) claims incompatible type

### ISSUE THREAD

**Issue by janosh** [VirtusLab/pandas-stubs#44]
Just tried out `pandas-stubs` for the first time and got a type error on a line that works as intended.

>  error: Argument 1 to "concat" has incompatible type "Dict[str, DataFrame]"; expected "Union[Iterable[DataFrame], Mapping[Optional[Hashable], DataFrame]]"

```py
pd.concat({"a": pd.DataFrame([1, 2, 3]), "b": pd.DataFrame([4, 5, 6])}, axis=1)
>>> 	a	b
	0	0
0	1	4
1	2	5
2	3	6

```

Is this an issue with the type declaration or am I misusing `pd.concat`?

**Comment by zkrolikowski-vl** [comment]
Hi @janosh 

you're using `pd.concat` correctly and type declaration must be fixed, as it is coherent with the pandas documentation but it doesn't work practically. I'll try to work this out soon and release a new version.

**Comment by zkrolikowski-vl** [comment]
This seems to work, with some code duplication, but it's not clear why:
https://github.com/VirtusLab/pandas-stubs/pull/45

I'll try to work out why that is.

**Comment by zkrolikowski-vl** [comment]
I wasn't able to isolate this issue with the boilerplate declaration syntax, but this is such a big an issue that I've decided to apply the fix.

**Comment by janosh** [comment]
was this part of the `pandas-stubs-1.1.0.11` 3 days ago? I just updated and still getting that error.

**Comment by zkrolikowski-vl** [comment]
Yes. Could you tell me which version of Python, Mypy and Pandas are you using?

**Comment by janosh** [comment]
```txt
python==3.8.5
pandas==1.2.4
pandas-stubs==1.1.0.11
```

The error is occurring on [this line](https://github.com/janosh/tensorboard-reducer/blob/dcf7e36f64a213a96d6533ddbf600e1b3e3c51e7/tensorboard_reducer/write.py#L129).

**Comment by janosh** [comment]
Small update: this minimal example still raises a type error with `pandas-stubs==1.2.0.1``:

```py
import pandas as pd

df = pd.DataFrame([1])

dic = {"a": df}

pd.concat(dic)
```

> t.py:8: error: Argument 1 to "concat" has incompatible type "Dict[str, DataFrame]"; expected "Iterable[DataFrame]"
Found 1 error in 1 file (checked 1 source file)

**Comment by zkrolikowski-vl** [comment]
Sorry. I can see that this is still an issue. 
mypy keeps using the wrong overloaded variant: https://github.com/VirtusLab/pandas-stubs/blob/f521cfb5a2bda425f20d96281999791b01d4833b/third_party/3/pandas/core/reshape/concat.pyi#L11 

I'll see what we can do about it.

**Comment by zkrolikowski-vl** [comment]
@janosh Made an ugly but inevitable fix: https://github.com/VirtusLab/pandas-stubs/pull/84 Could you check the test cases cover your use cases?

**Comment by janosh** [comment]
@zkrolikowski-vl Thanks! Test cases do indeed cover my use case.

**Comment by zkrolikowski-vl** [comment]
@janosh A new version 1.2.0.15 should already be available on PyPI and will be available on Conda Forge by Monday.

**Comment by janosh** [comment]
Excellent! Fix confirmed. No more type errors on `df = pd.concat({"a": df})` and auto-completion for `pd.json_normalize` is also working. Thanks a lot!

**Comment by janosh** [comment]
Sorry, I think I jumped the gun here. Still getting a type error on `pandas-stubs==1.2.0.16`:

![Screen Shot 2021-09-10 at 16 20 01](https://user-images.githubusercontent.com/30958850/132878708-77b6f89b-30bc-4405-b1bc-a076558adc7e.png)
