### ISSUE TITLE
DataFrame.from_dict false positive while linting

### ISSUE THREAD

**Issue by msdrigg** [VirtusLab/pandas-stubs#51]
I am getting this error while linting on   mypy version 0.902 with python version 3.8.10
> error: Argument 1 to "from_dict" of "DataFrame" has incompatible type "Dict[str, List[Any]]"; expected "Dict[str, Union[Union[Union[ExtensionArray, ndarray], Index, Series], Series, Dict[Union[int, str], Any]]]"

This is a false alarm because in pandas own [examples](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_dict.html) they have this code
```python
>>> data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
>>> pd.DataFrame.from_dict(data)
```

The offending line in the stubs is [here](https://github.com/VirtusLab/pandas-stubs/blob/master/third_party/3/pandas/core/frame.pyi#L95)

```python
@classmethod
def from_dict(cls: Any, data: Dict[str, Union[AnyArrayLike, Series, Dict[Column, Dtype]]], other_kwargs:...
```

It appears that data should be extended to include `List` in addition to `Dict`, `Series`.

In fact, looking at the source code for pandas, the data argument is passed into `Dataframe.__init__` directly, and it appears that if any data passed to `Dataframe.__init__` doesn't match a more specific type, it gets passed to [`maybe_iterable_to_list`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/common.py#L283). 

Should `Iterable` or `List` be added to the list of valid types here?

If someone has an answer, I can write a PR

**Comment by joannasendorek** [comment]
Hi! Thank you for reaching to us about this issue. I reviewed the definition of `from_dict` and discovered some other problems with it. Therefore the proposed fix: https://github.com/VirtusLab/pandas-stubs/pull/52 It also contains test added.

**Comment by msdrigg** [comment]
Thanks!
