### ISSUE TITLE
Repository tags and releases do not reflect PyPi versions

### ISSUE THREAD

**Issue by aholmes** [VirtusLab/pandas-stubs#53]
Hi,

I updated pandas-stubs from 1.1.0.7 to 1.1.0.11 and wanted to see what specifically changed. I came here hoping to see a tag or release, but cannot find either. It would really help with discoverability and usage efforts if the repository tag versions (at minimum, releases would be nice too) reflected release versions on PyPi/vice versa.

**Comment by zkrolikowski-vl** [comment]
Hi @aholmes.

Will prioritize this. Thanks for indicating that this is an issue.

**Comment by joannasendorek** [comment]
Hi @aholmes we have just added version bump commits into our repository. It should improve readability a lot. Do you think adding extra tags would be helpful too? What do you think about current solution, has it help?

**Comment by aholmes** [comment]
Hi, the version bump commits might be useful, but I think in relation to this issue they are kind of duplicating the functionality of Git tags and GitHub releases. If the bump commit is intended to be a defining line for your PyPi releases, I would suggest also creating a Git tag from that. I think that would help with discoverability, in part because it's a standard part of Git. As for GitHub releases, they can be very useful for packaging up everything that went into that version bump, but this may not be as important given the use of PyPi.

**Comment by zkrolikowski-vl** [comment]
Planned to include tags and released in the CI but never got the PR merged.

Closing this PR as pandas-stubs has moved to another repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

The new repository doesn't include tags but I can't imagine not adding them at some point.

**Comment by aholmes** [comment]
Great, thank you for the update. Think I should open the same issue there? :)

**Comment by zkrolikowski-vl** [comment]
Yes. Hopefully with faster resolution :D
