### ISSUE TITLE
Type annotation for pipe()

### ISSUE THREAD

**Issue by nanne-aben** [VirtusLab/pandas-stubs#54]
First of all, great project! Very happy user here :)

Now to my point: currently `pipe()` is annotated to return `Any`. This means the following doesn't result in a mypy error, even though it really should.
```
import pandas as pd

def foo(df: pd.DataFrame) -> pd.DataFrame:
    return df

df: int = (
    pd.DataFrame({'a': [1]})
    .pipe(foo)
)
```
I think we can do better if we define `pipe()` as follows:
```
from typing import TypeVar, Callable, Tuple, Union

V = TypeVar("V")

def pipe(self, func: Union[Callable[..., V], Tuple[Callable[..., V], str]], *args, **kwargs) -> V: ...
```
Now the first example throws a mypy error. 

There's one edge case that I came across though: apparently it's possible to pass something other than a callable to `pipe()`.
```
df = (
    pd.DataFrame({'a': [1]})
    .pipe(1)
)
```
After which `df == 1`. Not sure why anyone would want to do that, but sure. We can incorporate that using:
```
from typing import TypeVar, Callable, Tuple, Union, overload

V = TypeVar("V")

@overload
def pipe(self, func: Union[Callable[..., V], Tuple[Callable[..., V], str]], *args, **kwargs) -> V: ...

@overload
def pipe(self, func: V, *args, **kwargs) -> V: ...
```

I can open a PR if you're interested. First wanted to check what you thought on the matter. Also, I noticed `pipe()` is defined in a number of places, and I wasn't sure if we need to annotate all of them (I suppose we should?).

**Comment by zkrolikowski-vl** [comment]
Hi @nanne-aben. This all sounds very sensible.

You're right about allowing people passing something else other than callable. It's a bit strange that the type checker doesn't always go for the second overload when types don't match. 🤔 Anyway good work.

It would be best to cover as many of pipe definitions as possible, as long as they follow this interface. However don't feel compelled to cover all of them. Especially the ones in base classes like `_GroupBy`. Our main AIM is typing the API.

I'll gladly take a look at a PR.

**Comment by nanne-aben** [comment]
Thanks!

> It's a bit strange that the type checker doesn't always go for the second overload when types don't match. 🤔 

I'm not sure I understand, can you elaborate? 

The type checker will always go for the first one, and if that doesn't work try the second one (which in our case is more general). In fact, if you define them such that the general one comes first, mypy actually complains about that 
```
@overload
def pipe(self, func: V, *args, **kwargs) -> V: ...

@overload
def pipe(self, func: Union[Callable[..., V], Tuple[Callable[..., W], str]], *args, **kwargs) -> V: ...

# mypy: overloaded function signature 2 will never be matched
```
But maybe I'm missing your point completely?

> It would be best to cover as many of pipe definitions as possible, as long as they follow this interface.

Cool, will do!

**Comment by zkrolikowski-vl** [comment]
You're right. These definitions are set up correctly. Thanks :)

**Comment by nanne-aben** [comment]
Here's the PR:
https://github.com/VirtusLab/pandas-stubs/pull/55

This is my first PR on github (I'm more used to gitlab), so let me know if I did something weird :p 

I wrote a small test script that shows that this works as expected (all of these should raise a mypy error):
```
import pandas as pd

def foo(df: pd.DataFrame) -> pd.DataFrame:
    return df

a: int = (
    pd.DataFrame({'a': [1]})
    .pipe(foo)
)

b: int = (
    pd.DataFrame(
        {
            'price': [10, 11, 9, 13, 14, 18, 17, 19],
            'volume': [50, 60, 40, 100, 50, 100, 40, 50]
        }
    )
    .assign(week_starting=pd.date_range('01/01/2018', periods=8, freq='W'))
    .resample('M', on='week_starting')
    .pipe(foo)
)

c: int = (
    pd.DataFrame({'a': [1], 'b': [1]})
    .groupby('a')
    .pipe(foo)
)

d: int = (
    pd.DataFrame({'a': [1], 'b': [1]})
    .style
    .pipe(foo)
)
```

Of note, I haven't tested `third_party/3/pandas/core/common.pyi`, because I'm not sure where in pandas it's used.

Finally, for the annotations in `third_party/3/pandas/core/resample.pyi` to be of any effect, I had to change the return type of `DataFrame.resample()` from `Any` to `Resampler` (in `third_party/3/pandas/core/generic.pyi`). Judging by the pandas documentation, that should be alright, but I don't use resampling very often, so maybe best to have another pair of eyes check that.

Let me know what you think!

**Comment by zkrolikowski-vl** [comment]
Merged PR https://github.com/VirtusLab/pandas-stubs/pull/55. Thanks for contributing. :)
