### ISSUE TITLE
Pandas Timestamp object operations not recognized

### ISSUE THREAD

**Issue by radohristov** [VirtusLab/pandas-stubs#71]
Hi there,

I have the following code:

import pandas as pd
pts: pd.Timestamp=pd.to_datetime("4-5-2019")

td: pd.Timedelta = pts-pts

Running mypy I'm getting the following error:
 pmypy.py:4: error: Unsupported left operand type for - ("Timestamp")

Python Version 3.9.4
pandas Version: 1.3.2
pandas-stubs Version: 1.2.0.11 
mypy Version: 0.910

**Comment by zkrolikowski-vl** [comment]
Hi @radohristov. This obviously invalid. I'll prepare a PR to fix that.

**Comment by zkrolikowski-vl** [comment]
@radohristov Please consider if https://github.com/VirtusLab/pandas-stubs/pull/77 will help you

**Comment by zkrolikowski-vl** [comment]
@radohristov Fixed by https://github.com/VirtusLab/pandas-stubs/pull/77
