### ISSUE TITLE
No stub for pd.json_normalize

### ISSUE THREAD

**Issue by janosh** [VirtusLab/pandas-stubs#76]
Based on findings in https://github.com/microsoft/pylance-release/issues/1738, it appears that this package is missing a stub for `pd.json_normalize`.

**Comment by joannasendorek** [comment]
Thanks for reporting. I will prepare PR for that.

**Comment by joannasendorek** [comment]
Hi @janosh, could you please see PR: #82 ? Are there any specific use cases you have in your project that we could add to our test snippets?

**Comment by janosh** [comment]
Thanks, #82 looks great! `json_normalize` takes both a list of dicts (which you're testing) as well as a single dict. Not sure if that warrants additional testing but thought I'd mention it.

**Comment by joannasendorek** [comment]
Hi! Thanks for suggestion, I added one case specifically for that.

**Comment by janosh** [comment]
I forgot to mention `pd.json_normalize` can also take a `pd.Series` or `pd.DataFrame`. I often use this sort of operation:

```py
df_outputs = pd.json_normalize(df["output"])
```

if the elements in `df["output"]` are identically structured dicts and I want each key to end up as its own column in a new df.
