### ISSUE TITLE
mypy  Cannot find implementation or library stub for module named "pandas" after installing it

### ISSUE THREAD

**Issue by TheBubblePopped** [VirtusLab/pandas-stubs#86]
I use venv in combination with python 3.9

I installed it via pip with the activated venv environment.

**Comment by joannasendorek** [comment]
Hi! Could you please provide logs and the commands you ran to install. Environment definitions would be welcome too. We need more information in order to reproduce your problem. Thanks!

**Comment by BryceStevenWilley** [comment]
I ran into this as well, but resolved it. My issue was that while I installed `pandas-stubs` in the activated venv environment, I had installed mypy with `sudo apt install mypy` (probably from some tutorial when I was starting with mypy), so mypy wasn't seeing the pandas stubs. You should be able to see if your mypy is the correct one with `which mypy`, and it should be in the same venv folder that's activated (`.../venv/bin/mypy`).

**Comment by zkrolikowski-vl** [comment]
pandas-stubs has moved to another repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

Closing.
