### ISSUE TITLE
about the code version

### ISSUE THREAD

**Issue by jinwuxia** [VirtusLab/pandas-stubs#9]
pandas project has several branches or versions.
pandas-stubs only have one branch. My question is, which version of pandas source code does pandas-stubs corresponds to?

Thanks.

**Comment by zkrolikowski-vl** [comment]
Currently this corresponds to Pandas version `1.0.4`. Versions for to newer Pandas releases will be added in the future, each on appropriate branch and with a version tag.

Although the differences between the API's aren't substantial and you can still try using this project for a newer Pandas version e.g.  1.1 and 1.2, you might run into some minor issues, namely when using new features. 

Thanks for your interest in our project @jinwuxia . We'll try to bring better versioning as soon as possible.

**Comment by jinwuxia** [comment]
@zkrolikowski-vl 
Thanks for your quick reply. 
It really helps me a lot!
