### ISSUE TITLE
add __add__ for pd.Timestamp

### ISSUE THREAD

**Issue by AlesiRowland** [VirtusLab/pandas-stubs#92]
I'm getting a
 ```
error: Unsupported left operand type for + ("Timestamp")
```

When calling `pd.Timestamp("20200101") + BDay(1)`
When looking at the stub, there's no implementation for __add__, I might be being naive (new to stub libs), but I assume adding a stub for this method would resolve the error?

**Comment by zkrolikowski-vl** [comment]
I had been working on a solution for a while: https://github.com/VirtusLab/pandas-stubs/pull/77

It's technically working but I get the following error for Python 3.6 and Python 3.7:
```
tests/snippets/test_timestamp.py:26: error: Incompatible types in assignment (expression has type "datetime", variable has type "Timestamp")
```

I'm planning to make it work but this issue blocks me.

**Comment by zkrolikowski-vl** [comment]
I had a moment of clarity and fixed it. @AlesiRowland could you take a look at the test file https://github.com/VirtusLab/pandas-stubs/pull/77/files#diff-3e336eaaa7d457901c2337d6dc8c6809a911fde68439e160887da5642aacdf98 ? Let me know in the comments if there's any other case to cover.

**Comment by zkrolikowski-vl** [comment]
This is fixed by: https://github.com/VirtusLab/pandas-stubs/pull/77
