### ISSUE TITLE
Add "time" attribute to "DatetimeIndex"

### ISSUE THREAD

**Issue by claudio-ebel** [VirtusLab/pandas-stubs#96]
The `time` attribute of `DatetimeIndex` seems not to be implemented.

Minimal working example:
```python
# file tmp.py
import pandas as pd

dr = pd.date_range(start='2020-1-1', periods=3)
print(dr.time)
```

Then executing `mypy tmp.py` results in

```
tmp.py:5: error: "DatetimeIndex" has no attribute "time"
Found 1 error in 1 file (checked 1 source file)
```

while the execution `python tmp.py` of the code works perfectly. Tested with

```
Python 3.9.7
numpy==1.21.2
pandas==1.3.2
pandas-stubs==1.2.0.22
```

**Comment by zkrolikowski-vl** [comment]
No solution was provided but pandas-stubs has moved to another repository and will now be managed alongside pandas itself: https://github.com/pandas-dev/pandas-stubs

You might try using the newest version `pip install pandas-stubs==1.4.2.220626` which comes from that repository.  If it doesn't work please considering opening an issue in the new repository.
